name: Run Build and Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build-and-test-dotnet:
    name: Run Build and Test .NET
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Setup .NET 6.0 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore Nuget Packages
        run: dotnet restore

      - name: Build .NET Solution
        run: |
          dotnet build --no-restore /p:ContinuousIntegrationBuild=true --configuration Release
          
      - name: Run Unit Tests
        working-directory: ./DotnetTemplate.Tests
        run: |
          dotnet test DotnetTemplate.Tests.csproj -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:CoverletOutput=TestResults -p:SkipAutoProps=true -p:Threshold=80
          
#      - name: Run .NET Publish
#        run: |
#          dotnet publish "WebAppPath/WebAppProject.csproj" -r "linux-x64" -o "project-linux-build/src" --self-contained

#      - name: Drop Artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: project-linux-build
#          path: project-linux-build/src