trigger:
  branches:
    include:
      - develop

pr:
  branches:
    include:
      - develop

variables:
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
#  - name: backendProjectPath
#    value: 'MangoAPI.Presentation/MangoAPI.Presentation.csproj'
#  - name: frontEndProjectPath
#    value: 'MangoAPI.Client'

stages:
  - stage: 'Build_Test'
    jobs:
      - job: "Build"
        displayName: 'Build and Test'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - template: azure-pipelines-template.yml
